### ISSUE TITLE
Not Exiting After Nuxt Generate

### ISSUE THREAD

**Issue by stuible** [yann-yinn/nuxt-gustave#2]
First off, thank you so much for creating something that let me move away from nuxtent which has caused me multiple headaches.  Gustave is working great but when I generate I receive an warning:

The command 'nuxt generate' finished but did not exit after 5s This is most likely not caused by a bug in Nuxt.js Make sure to cleanup all timers and listeners you or your plugins/modules start.  Nuxt.js will now force exit.

It seems to be preventing nuxt from exiting even when it is done generating.

**Comment by yann-yinn** [comment]
Strange, thanks for your issue, will try to look this as soon as possible !

**Comment by yann-yinn** [comment]
fix in `0.5.4`
