### ISSUE TITLE
Exception: Cannot read property 'gustave' of undefined

### ISSUE THREAD

**Issue by michael-hillmann** [yann-yinn/nuxt-gustave#3]
Thank you for your work in this nice module. After some investigation, it worked for me smoothly.

I found, that with my nuxt configuration file:
~~~
./nuxt.config.js:
export default {
  ...
  modules: [
    'nuxt-gustave'
  ],
  gustave: {
    compilers: ['compilers/posts.js']
  },
  ...
}
~~~

The following exception occurs:
~~~
Cannot read property 'gustave' of undefined
~~~

With a small fix in gustave.js it works:
~~~
change of:
const nuxtConfig = require(path.resolve('./nuxt.config.js'))

to this:
const nuxtConfig = require(path.resolve('./nuxt.config.js')).default
~~~

Do you think this is a nuxt version dependency?
My setup is:
~~~
  "nuxt": "^2.6.3"
  "nuxt-gustave": "^0.5.2"
~~~

**Comment by menteora** [comment]
I've different error:

`TypeError: Cannot read property 'compilers' of undefined`

but, same solution and same version of nuxt and nuxt-gustave.

**Comment by yann-yinn** [comment]
Thanks for the report. That 's pretty strange, `require` is supposed to return the default export without being explicit, i don't understand what happens here ...

**Comment by yann-yinn** [comment]
Okay, don't know why but it some cases config is wrapped in a `default` key, sometimes not, i added a fix and publish it on npm, please let me know if it's ok for you : `0.5.3`

**Comment by michael-hillmann** [comment]
I can confirm. With version 0.5.3 this issue is fixed.
